#!/usr/bin/env bash
# verify-bug18.sh — in-container verification of the Bug #18 fix.
#
# Called from run-in-ps4-container.sh as step [6/6] after the PKG
# is built. Asserts the post-#95/#96 .pkg is materially equivalent
# to upstream pPlay 3.8 (33 MB ± 1 MB) and contains the same 5 PS4
# system files in its file table.
#
# The expected file names are read at runtime from
# docs/bug-18-expected-pkg-files.txt so the verifier never drifts
# from the source of truth (issue #97 AC #2 says "every file
# enumerated by #94's audit" — that list lives in the doc, the
# script must self-update from it).
#
# Writes a verification report to build/bug-18-verification.txt that
# the host can read back via the bind-mount at pplay-fork/build/.
# The user copies the SHA-256 from there into
# docs/ps4-test-report.md (issue #97 acceptance #5).
#
# Failure: exit 1 with a clear message naming which assertion tripped.
# The PKG artifacts from the failed run are left on disk for debugging.

set -euo pipefail

cd /work
# `audit_upstream_pkg.py` lives at the repo root, not inside
# pplay-fork/. Add the parent so `from scripts.audit_upstream_pkg`
# resolves regardless of which cwd python is invoked from.
export PYTHONPATH="/work/..:${PYTHONPATH:-}"

PKG="build/PPLA00001.pkg"
REPORT="build/bug-18-verification.txt"
EXPECTED_LIST="docs/bug-18-expected-pkg-files.txt"

# Upstream is 33,882,112 B (33 MB); we allow [32 MB, 34 MB] per
# issue #97 AC. The upper bound is 1.13 MB above upstream (matches
# "± 1 MB" in human terms; the lower bound is 1.33 MB below).
MIN_SIZE=$((32 * 1024 * 1024))   # 33,554,432
MAX_SIZE=$((34 * 1024 * 1024))   # 35,651,584

ok() { echo "  ok  $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

# Pre-flight.
[ -f "$PKG" ] || fail "$PKG not found — did step [4/5] run?"
[ -f "$EXPECTED_LIST" ] || fail "$EXPECTED_LIST not found — Bug #18 source of truth missing"
SIZE=$(stat -c %s "$PKG")
echo "==> PKG: $PKG ($SIZE B)"

# 1. Size in 33 MB ± 1 MB.
[ "$SIZE" -ge "$MIN_SIZE" ] || fail "PKG is $SIZE B; under 32 MB lower bound (Bug #18 NOT fixed)"
[ "$SIZE" -le "$MAX_SIZE" ] || fail "PKG is $SIZE B; over 34 MB upper bound (suspiciously large)"
ok "size $SIZE B is in [32 MB, 34 MB] (33 MB ± 1 MB)"

# 2. PKG magic: 7f 43 4e 54 (.CNT, OpenOrbis PkgTool.Core output).
MAGIC=$(od -An -tx1 -N4 "$PKG" | tr -d ' \n')
[ "$MAGIC" = "7f434e54" ] || fail "PKG magic is $MAGIC, expected 7f434e54"
ok "PKG magic is 7f434e54 (.CNT)"

# 3. eboot.bin magic: 4f 15 3d 1d (SCE SELF wrapper from create-fself).
EBOOT="build/eboot.bin"
SELF_MAGIC=$(od -An -tx1 -N4 "$EBOOT" | tr -d ' \n')
[ "$SELF_MAGIC" = "4f153d1d" ] || fail "eboot.bin magic is $SELF_MAGIC, expected 4f153d1d"
ok "eboot.bin magic is 4f153d1d (SCE SELF)"

# 4. File-table parity: our PKG must contain every file in EXPECTED_LIST.
#    parse_pkg_names is fast (reads only the file-table header, no body).
mapfile -t EXPECTED_FILES < <(grep -v '^\s*#' "$EXPECTED_LIST" | grep -v '^\s*$')
ACTUAL_FILES=$(python3 -c "
from scripts.audit_upstream_pkg import parse_pkg_names
print('\n'.join(sorted(parse_pkg_names('$PKG'))))
")
for f in "${EXPECTED_FILES[@]}"; do
    f=$(echo "$f" | xargs)  # trim whitespace from the file
    echo "$ACTUAL_FILES" | grep -qx "$f" || fail "PKG file table is missing $f (Bug #18 NOT fixed)"
done
ok "file table contains all ${#EXPECTED_FILES[@]} expected files:"
echo "$ACTUAL_FILES" | sed 's/^/      /'

# 5. Write the verification report (host reads it back via the bind mount).
SHA256=$(sha256sum "$PKG" | awk '{print $1}')
COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
{
    echo "# Bug #18 verification report (issue #97)"
    echo "# Generated by pplay-fork/scripts/verify-bug18.sh"
    echo "timestamp:    $TIMESTAMP"
    echo "commit:       $COMMIT"
    echo "pkg_path:     $PKG"
    echo "pkg_size:     $SIZE bytes"
    echo "pkg_sha256:   $SHA256"
    echo "pkg_magic:    $MAGIC"
    echo "eboot_magic:  $SELF_MAGIC"
    echo "files_in_table:"
    echo "$ACTUAL_FILES" | sed 's/^/  - /'
} > "$REPORT"

echo "==> ok: report written to $REPORT"
cat "$REPORT"
